[uv]
python = "{{ cookiecutter.python_version }}"
system-python = false
venv = ".venv"

[uv.pip]
resolution = "highest"
compile = true
generate-hashes = true

[uv.pip.index]
url = "https://pypi.org/simple"
